development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://rhrduhbjoklquk:8ae61f9e68784943993f79eb02d02290cd900c1d8bd5ccc6294ae299add88ef6@ec2-23-21-246-25.compute-1.amazonaws.com:5432/dakvlch3hh11rb
  channel_prefix: apptakeone_production
